<?php
return [
	'password',
	'name'=>'confirm_password',
	'text'=>'确认密码',
	'attrs'=>[
		'class'=>'form-control',
		'required'=>1,
		'placeholder'=>'请输入密码',
		'autocomplete'=>'new-password',
	],
	'event'=>[
		'beforeAdd'=>function($element){
			$controller=\xqkeji\App::getController();
			$actionName=$controller->getActionName();
			if($actionName=='edit')
			{
				$attributes=$element->getAttrs();
				unset($attributes['required']);
				$attributes['placeholder']='请输入确认密码(不用修改密码时，不要填写)';
				$element->setAttrs($attributes);
				$validators=$element->getValidators();
				$validator=$validators[0];
				$validator->setOption('allowEmpty',true);
			}
		},
	],
	'filters'=>['string'],
	'validators'=>[
		[
			'confirm',
			'allowEmpty'=>false,
			'with'=>'password',
		]
	],
];