<?php
return [
	'assets'=>[
        'js'=>[
            'xq-admin-layout'=>[
                'bootstrap/js/bootstrap.bundle.min.js',
                'overlayscrollbars/browser/overlayscrollbars.browser.es5.min.js',
                'xq-admin-layout/js/xq-admin-layout.min.js',
            ],
            'xq-admin-page'=>[
                'bootstrap/js/bootstrap.bundle.min.js',
                'xq-admin-page/js/xq-admin-page.min.js',
            ],
        ],
        'css'=>[
            'xq-admin-layout'=>[
                'bootstrap/css/bootstrap.min.css',
                'bootstrap-icons/font/bootstrap-icons.css',
                'overlayscrollbars/styles/overlayscrollbars.min.css',
                'xq-admin-layout/css/xq-admin-layout.min.css',
            ],
            'xq-admin-page'=>[
                'bootstrap/css/bootstrap.min.css',
                'bootstrap-icons/font/bootstrap-icons.css',
                'xq-admin-page/css/xq-admin-page.min.css',
            ],
        ],
        'directory'=>[
			'css/fonts'=>[
				'bootstrap-icons/font/fonts'
			],
		],
    ]
];